### ISSUE TITLE
Convert DBC files to Python/Scala files

### ISSUE THREAD

**Issue by OneCricketeer** [confluentinc/confluent-azure-examples#2]
We shouldn't need databricks accounts for reading the code. 

See export options here - https://docs.databricks.com/notebooks/notebooks-manage.html#export-a-notebook

**Comment by OneCricketeer** [comment]
Hi @JakeBogie , will the new workshops show source code in a non-proprietary file format?

**Comment by JakeBogie** [comment]
We don't have plans at this time to update that workshop. With that said we could always review the need for an updated version of the workshop and plan for it to be part of an upcoming cycle.
